#!/usr/bin/env bash
# Transfers a file from our client to a server
function usage(){
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
}
# check if number of arguments are correct
if [ "$#" -lt 3 ]; then
    usage
    exit 1
fi
#assign aguments to variables
file_path=$1
server_ip=$2
ssh_username=$3
ssh_key_path=$4
# check if the SSH key file exist
if [ ! -f "$ssh_key_path" ]; then
    echo "SSH key file not found"
    exit 1
fi
# transfer file using scp
scp -o "StrictHostKeyChecking=no" -i "$ssh_key_path" -P 22 "$file_path" "$ssh_username@$server_ip:~/"
# check if the transfer was successful
if [ $? -eq 0 ]; then
    echo "File transfer successful"
else
    echo "File transfer failed"
fi
