#!/usr/bin/env bash
# Install Nginx
apt-get update
apt-get install -y nginx

# Start Nginx
service nginx start

# Configure Nginx to listen on port 80
sed -i 's/listen 80 default_server;/listen 80 default_server;/g' /etc/nginx/sites-available/default

# Restart Nginx
service nginx restart
